module.exports={
    baseUrl:'https://dev.to/',
    isHeadless:false,
    slowMo:0,
    isDevtools:false,
    launchTimeout:20000,
    waitingTimeout:20000,
    viewportWidth:1200,
    viewportHeight:1000
}